### ISSUE TITLE
Port for yii2

### ISSUE THREAD

**Issue by philippfrenzel** [raoul2000/simpleWorkflow#1]
Hi, are you planning a port for yii2 - I'm currently planning a new intranet side and I used your extension successfull with yii.. so as i want to make the new one in yii2, it would be great to know if you have any plans?

**Comment by mbetel** [comment]
Hi raoul, do you have any news on the Yii2 port? I'd love to use this in a new project.

**Comment by raoul2000** [comment]
Hi mbetel,
yes, it going pretty well and I'm confident a first alpha release will be available during February. I hope it will be useful to you and others.

**Comment by mbetel** [comment]
Great! I'd love to test it! Using your swf extension in a yii 1 project right now.

**Comment by raoul2000** [comment]
yii2-workflow repository created : https://github.com/raoul2000/yii2-workflow
