### ISSUE TITLE
please add composer.json

### ISSUE THREAD

**Issue by cornernote** [raoul2000/simpleWorkflow#11]
please add a license and composer.json and register your extension at www.packagist.org

**Comment by raoul2000** [comment]
Ok, but first can you explain how it can be usable with Yii1 ? I though it was only possible for yii2 and composer support.

**Comment by cornernote** [comment]
Just add it as a library (not a yii extension).

It will allow me to add it to my projects composer.json so that i can keep up-to-date with your latest versions instead of importing the code into my project.

I do it with all of my Yii1 modules, eg:
https://github.com/cornernote/yii-audit-module

I also do it with non-yii code.  It makes it really easy to reuse libraries.

**Comment by raoul2000** [comment]
Thank for the clarification ... I will do that soon.

**Comment by raoul2000** [comment]
Done.

**Comment by cornernote** [comment]
Awesome!  Thanks.

If you could also add a LICENSE file that would really help.  I can't use this code on my current project without one.

**Comment by cornernote** [comment]
Although unrelated, just wanted to give feedback... I used SW on a project a few years back for some quite complex workflow.  Models were like this:

Job -(hasMany)> Item -(hasMany)> Unit -(belongsTo)> Package -(belongsTo)> Pickup

Pickup -(hasMany)> Package -(hasMany)> Unit -(belongsTo)> Item -(belongsTo)> Job

When a Pickup was collected, it marks the Packages complete.
When a Package was complete, it marks the Unit complete.
When all Units are complete, it marks the Item complete.
When all Items are complete, it marks the Job complete.

The workflows were in MySQL and all controlled (including transitions, etc) via pages in the yii app.  Items had a "type" field, and each type of Item had its own workflow, and also determined the workflow for the related Units.

There were obviously more complexities than this, however it gives you a good idea of how your package was used.

SW was a fantastic helper to make all of this work.  Thank you for making this code available.

**Comment by raoul2000** [comment]
I will add the LICENSE.md file soon.

Thank you for the interesting and valuable feedback on SW. It is important for me to understand possible real life use cases, in order to improve this piece of software....

**Comment by raoul2000** [comment]
LICENSE added
